/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Operation_constants.h"

namespace Chad {

const OperationConstants g_Operation_constants;

OperationConstants::OperationConstants() {
}

} // namespace

