/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Operation_CONSTANTS_H
#define Operation_CONSTANTS_H

#include "Operation_types.h"

namespace Chad {

class OperationConstants {
 public:
  OperationConstants();

};

extern const OperationConstants g_Operation_constants;

} // namespace

#endif
